// Code generated by protoc-gen-go.
// source: github.com/paralin/gogame/gogame.proto
// DO NOT EDIT!

/*
Package gogame is a generated protocol buffer package.

It is generated from these files:
	github.com/paralin/gogame/gogame.proto

It has these top-level messages:
	NetEntity
	NetComponent
	ComponentMeta
*/
package gogame

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameOperatingMode int32

const (
	GameOperatingMode_LOCAL  GameOperatingMode = 0
	GameOperatingMode_REMOTE GameOperatingMode = 1
)

var GameOperatingMode_name = map[int32]string{
	0: "LOCAL",
	1: "REMOTE",
}
var GameOperatingMode_value = map[string]int32{
	"LOCAL":  0,
	"REMOTE": 1,
}

func (x GameOperatingMode) String() string {
	return proto.EnumName(GameOperatingMode_name, int32(x))
}
func (GameOperatingMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

//
// Networked representation of an entity.
type NetEntity struct {
	Id        uint32          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ParentId  uint32          `protobuf:"varint,2,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	Component []*NetComponent `protobuf:"bytes,3,rep,name=component" json:"component,omitempty"`
}

func (m *NetEntity) Reset()                    { *m = NetEntity{} }
func (m *NetEntity) String() string            { return proto.CompactTextString(m) }
func (*NetEntity) ProtoMessage()               {}
func (*NetEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NetEntity) GetComponent() []*NetComponent {
	if m != nil {
		return m.Component
	}
	return nil
}

//
// Networked representation of a component.
type NetComponent struct {
	// ID of implementation of component
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Initial state, deterministic message serialized
	InitData []byte `protobuf:"bytes,2,opt,name=init_data,json=initData,proto3" json:"init_data,omitempty"`
}

func (m *NetComponent) Reset()                    { *m = NetComponent{} }
func (m *NetComponent) String() string            { return proto.CompactTextString(m) }
func (*NetComponent) ProtoMessage()               {}
func (*NetComponent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

//
// Metadata for a component type.
type ComponentMeta struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ComponentMeta) Reset()                    { *m = ComponentMeta{} }
func (m *ComponentMeta) String() string            { return proto.CompactTextString(m) }
func (*ComponentMeta) ProtoMessage()               {}
func (*ComponentMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*NetEntity)(nil), "gogame.NetEntity")
	proto.RegisterType((*NetComponent)(nil), "gogame.NetComponent")
	proto.RegisterType((*ComponentMeta)(nil), "gogame.ComponentMeta")
	proto.RegisterEnum("gogame.GameOperatingMode", GameOperatingMode_name, GameOperatingMode_value)
}

func init() { proto.RegisterFile("github.com/paralin/gogame/gogame.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xd2, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2b, 0x2d, 0x4e, 0x2d, 0xca, 0x4f, 0xca, 0x2f,
	0xc9, 0x4c, 0x2e, 0xd6, 0x4f, 0xcf, 0x4f, 0x4f, 0xcc, 0x4d, 0x85, 0x52, 0x7a, 0x05, 0x45, 0xf9,
	0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x52, 0x0e, 0x17, 0xa7, 0x5f, 0x6a, 0x89, 0x6b, 0x5e, 0x49,
	0x66, 0x49, 0xa5, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6f, 0x10,
	0x90, 0x25, 0x24, 0xcd, 0xc5, 0x59, 0x90, 0x58, 0x94, 0x9a, 0x57, 0x12, 0x0f, 0x14, 0x66, 0x02,
	0x0b, 0x73, 0x40, 0x04, 0x3c, 0x53, 0x84, 0x8c, 0xb8, 0x38, 0x81, 0x36, 0x15, 0xe4, 0xe7, 0x01,
	0xb9, 0x12, 0xcc, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x22, 0x7a, 0x50, 0x3b, 0x80, 0x46, 0x3a, 0xc3,
	0xe4, 0x82, 0x10, 0xca, 0x94, 0xac, 0xb9, 0x78, 0x90, 0xa5, 0xb0, 0x59, 0x98, 0x99, 0x97, 0x59,
	0x12, 0x9f, 0x92, 0x58, 0x92, 0x08, 0xb6, 0x90, 0x27, 0x88, 0x03, 0x24, 0xe0, 0x02, 0xe4, 0x2b,
	0xc9, 0x73, 0xf1, 0xc2, 0x75, 0xfa, 0xa6, 0x96, 0x24, 0xa2, 0xeb, 0xd6, 0xd2, 0xe2, 0x12, 0x74,
	0x07, 0xda, 0xee, 0x5f, 0x90, 0x5a, 0x94, 0x58, 0x92, 0x99, 0x97, 0xee, 0x9b, 0x9f, 0x92, 0x2a,
	0xc4, 0xc9, 0xc5, 0xea, 0xe3, 0xef, 0xec, 0xe8, 0x23, 0xc0, 0x20, 0xc4, 0xc5, 0xc5, 0x16, 0xe4,
	0xea, 0xeb, 0x1f, 0xe2, 0x2a, 0xc0, 0x98, 0xc4, 0x06, 0x0e, 0x06, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x02, 0x7d, 0xce, 0x29, 0x35, 0x01, 0x00, 0x00,
}
