// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/gogame/components/transform/transform.proto
// DO NOT EDIT!

/*
Package transform is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/gogame/components/transform/transform.proto

It has these top-level messages:
	TransformPosition
	TransformScale
	TransformData
	TransformComponentInit
*/
package transform

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransformPosition struct {
	X int32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
}

func (m *TransformPosition) Reset()                    { *m = TransformPosition{} }
func (m *TransformPosition) String() string            { return proto.CompactTextString(m) }
func (*TransformPosition) ProtoMessage()               {}
func (*TransformPosition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TransformScale struct {
	XScale int32 `protobuf:"varint,1,opt,name=x_scale,json=xScale" json:"x_scale,omitempty"`
	YScale int32 `protobuf:"varint,2,opt,name=y_scale,json=yScale" json:"y_scale,omitempty"`
}

func (m *TransformScale) Reset()                    { *m = TransformScale{} }
func (m *TransformScale) String() string            { return proto.CompactTextString(m) }
func (*TransformScale) ProtoMessage()               {}
func (*TransformScale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TransformData struct {
	Position *TransformPosition `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
	Scale    *TransformScale    `protobuf:"bytes,2,opt,name=scale" json:"scale,omitempty"`
}

func (m *TransformData) Reset()                    { *m = TransformData{} }
func (m *TransformData) String() string            { return proto.CompactTextString(m) }
func (*TransformData) ProtoMessage()               {}
func (*TransformData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TransformData) GetPosition() *TransformPosition {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *TransformData) GetScale() *TransformScale {
	if m != nil {
		return m.Scale
	}
	return nil
}

type TransformComponentInit struct {
	Data *TransformData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *TransformComponentInit) Reset()                    { *m = TransformComponentInit{} }
func (m *TransformComponentInit) String() string            { return proto.CompactTextString(m) }
func (*TransformComponentInit) ProtoMessage()               {}
func (*TransformComponentInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TransformComponentInit) GetData() *TransformData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*TransformPosition)(nil), "transform.TransformPosition")
	proto.RegisterType((*TransformScale)(nil), "transform.TransformScale")
	proto.RegisterType((*TransformData)(nil), "transform.TransformData")
	proto.RegisterType((*TransformComponentInit)(nil), "transform.TransformComponentInit")
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/gogame/components/transform/transform.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x50, 0x3f, 0x4b, 0xc4, 0x30,
	0x14, 0xa7, 0xe2, 0x55, 0x7d, 0xa7, 0x82, 0x19, 0xb4, 0x82, 0x83, 0x74, 0x72, 0x90, 0x06, 0xce,
	0xc5, 0xd9, 0x13, 0xc1, 0x4d, 0xaa, 0xbb, 0xa4, 0xb5, 0x57, 0x03, 0x36, 0xaf, 0x24, 0xef, 0x20,
	0xf1, 0xd3, 0x7b, 0x4d, 0x73, 0xe9, 0x60, 0xb7, 0xf7, 0xde, 0xef, 0x2f, 0x0f, 0xd6, 0xad, 0xa4,
	0xef, 0x6d, 0x55, 0xd4, 0xd8, 0xf1, 0xcd, 0xd6, 0x34, 0x1a, 0x2b, 0x24, 0x59, 0x1b, 0xde, 0x62,
	0x2b, 0xba, 0x86, 0xef, 0xee, 0x3d, 0xaa, 0x46, 0x91, 0xe1, 0xa4, 0x85, 0x32, 0x1b, 0xd4, 0xdd,
	0x34, 0x15, 0xbd, 0x46, 0x42, 0x76, 0x12, 0x0f, 0x39, 0x87, 0x8b, 0x8f, 0xfd, 0xf2, 0x86, 0x46,
	0x92, 0x44, 0xc5, 0x4e, 0x21, 0xb1, 0x59, 0x72, 0x9b, 0xdc, 0x2d, 0xca, 0xc4, 0x0e, 0x9b, 0xcb,
	0x0e, 0xc6, 0xcd, 0xe5, 0x4f, 0x70, 0x1e, 0x05, 0xef, 0xb5, 0xf8, 0x69, 0xd8, 0x15, 0x1c, 0xd9,
	0x4f, 0x33, 0x8c, 0x41, 0x93, 0xda, 0x08, 0xb8, 0x00, 0x8c, 0xf2, 0xd4, 0x79, 0x20, 0xff, 0x85,
	0xb3, 0xe8, 0xf1, 0x2c, 0x48, 0xb0, 0x47, 0x38, 0xee, 0x43, 0xb8, 0xf7, 0x58, 0xae, 0x6e, 0x8a,
	0xa9, 0xf4, 0xbf, 0x82, 0x65, 0x64, 0x33, 0x0e, 0x8b, 0x29, 0x61, 0xb9, 0xba, 0x9e, 0x93, 0xf9,
	0xd0, 0x72, 0xe4, 0xe5, 0x2f, 0x70, 0x19, 0x81, 0xf5, 0xfe, 0x59, 0xaf, 0x4a, 0x12, 0xbb, 0x87,
	0xc3, 0xaf, 0x5d, 0x99, 0x50, 0x20, 0x9b, 0x73, 0x1a, 0xca, 0x96, 0x9e, 0x55, 0xa5, 0xfe, 0x95,
	0x0f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x9b, 0x4c, 0xf2, 0x91, 0x01, 0x00, 0x00,
}
